DCUSnSLab/DCU_Online_Judge_Backend

problem/views/admin.py
=> DCUC-25_문제 삭제시 제출물이 우선 삭제되도록 수정

Jenkinsfile
=> [GEN-143] jenkins file updated for deployments to test server

account/views/admin.py
- 관리자 - 관리자, 교수 모두 나오도록 설정
- 교수 - 본인 이름만 나오도록 설정
=> [GEN-205] 교수권한 강의 개설 시 개설자 목록 출력 오류

deploy/entrypoint.sh, deploy/supervisord.conf
--workers 6
--threads 4
--max-requests-jitter 30000
--max-requests 3000000
--keep-alive 32
=> [GEN-217] updated gunicorn setup

submission/urls/oj.py, submission/views/oj.py
**작성한 코드 본인 깃허브에 업로드하는 기능 추가**
=> [GEN-215] add GitHub upload

judge/dispatcher.py
=> develop branch pull request

utils/DBTasks/changeSampleColumValue.py
Problem 테이블에 samples 데이터 수정을 위한 스크립트
=> Gen 216 code run feature (develop branch)

problem/views/admin.py
GEB-289_get_problem_fix (develop branch)
=> GEN-286_get_problem_fix (develop branch)

account/serializers.py, account/views/oj.py, contest/urls/oj.py, contest/views/admin.py, contest/views/oj.py, lecture/views/admin.py, problem/views/oj.py
=> Gen 288 lecture contest exit (develop branch)

account/serializers.py, account/views/oj.py
=> GEN-204_select_user_language_fix (develop branch)

contest/serializers.py, contest/views/admin.py
=> GEN-214_copy_contest_lecture_fix (develop branch)

account/views/admin.py
=> GEN-252_AdminList_get_fix (develop branch)

submission/views/oj.py, utils/DBTasks/changeSampleColumValue.py
=> Gen 326 run result error fix (develop)

problem/views/admin.py, utils/DBTasks/changeSampleColumValue.py
예시 입출력을 테스트케이스에서 가져올때 첫 줄에 공백에 제거 수정
=> Gen 330 sample blank fix (develop branch)

submission/views/oj.py
실습, 과제 시작 전에 제출한 기록을 제외하고 보여주도록 되어있어서 주석 처리
=> GEN-442 Resolved disappear submission

submission/views/oj.py
Reverts DCUSnSLab/DCU_Online_Judge_Backend#40
=> Revert "GEN-442 Resolved disappear submission"

submission/views/oj.py
실습 시작 전 제출을 제외하고 출력하도록 되어있어서 주석 처리
=> GEN-442 Resolved desappear submission

judge/dispatcher.py, submission/views/oj.py
=> GEN-420_fix_run_code(develop)

account/serializers.py, contest/models.py, contest/views/oj.py, problem/views/oj.py
GEN-510_fix_test_exit (develop)
=> GEN-510_fix_test_exit (develop)

account/views/oj.py, deploy/nginx/locations.conf
=> 마스터 업데이트 #39

account/views/oj.py, contest/views/admin.py, contest/views/oj.py, judge/dispatcher.py, lecture/models.py, lecture/urls/oj.py, lecture/views/oj.py, problem/views/oj.py, submission/views/oj.py
=> Gen 572 ta/ra
